In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Part I: Write code to create plots so that each of the question can be answered, you do not need to give the actual answer

In [2]:
#look up table with columns Month (Jan, Feb ...) and Month ID (1,2,3...)
month_lookup = Table.read_table('./month_lookup.csv')
#raw weather data
weather_raw = Table.read_table('./weather.csv')
#join raw weather data and month look up table
weather=weather_raw.join('Month',month_lookup,'Month').select('Month','MonthID',
                                                              'Day Index','Quarter ID','High','Low','Rain')
weather.show(5)

In [3]:
month_lookup

Month | MonthID
Jan   | 1
Feb   | 2
Mar   | 3
Apr   | 4
May   | 5
Jun   | 6
Jul   | 7
Aug   | 8
Sep   | 9
Oct   | 10
... (2 rows omitted)

In [4]:
weather_raw

Day Index | Quarter ID | Month | High | Low  | Rain
1         | 1          | Jan   | 39   | 30.2 | Yes
2         | 1          | Jan   | 57   | 37.9 | Yes
3         | 1          | Jan   | 42.1 | 36   | Yes
4         | 1          | Jan   | 46.9 | 31.1 | No
5         | 1          | Jan   | 44.1 | 37.9 | No
6         | 1          | Jan   | 42.1 | 37   | No
7         | 1          | Jan   | 46.9 | 31.1 | No
8         | 1          | Jan   | 37.9 | 29.1 | No
9         | 1          | Jan   | 46   | 29.1 | No
10        | 1          | Jan   | 50   | 26.2 | No
... (355 rows omitted)

### Q1. Are there more raindy than  non raindy days?

In [ ]:
...

### Q2. What percentage of days  have a high above 72 degree? Hint: use bins parameter

In [ ]:
...

### Q3. Do hotter days tend to  also have hotter nights?

In [1]:
...

Ellipsis

## Part II:  Group/pivot function practice: write code to reproduce each of the tables shown below

### Table 1
<img src="tables/table1.png" width="150" height="200"/>

In [ ]:
#table 1 (days in each month that has available data)
...

### Table 2
<img src="tables/table2.png" width="200" height="200"/>

In [ ]:
#table 2 (similar as table 1, nicely ordered)
...

### Table 3
<img src="tables/table3.png" width="200" height="200"/>

In [ ]:
#table 3
...

### Table 4
<img src="tables/table4.png" width="200" height="200"/>

In [ ]:
#table 4 (mean of high temperature for first quarter)
...

### Table 5
<img src="tables/table5.png" width="200" height="200"/>

In [ ]:
#table 5 (count of rainy and non-rainy days for each month in first quarter)
...

### Table 6
<img src="tables/table6.png" width="500" height="500"/>

In [ ]:
#table 6 (counts of rainy and non-rainy dates for each month of the year)
...

### Table 7
<img src="tables/table7.png" width="600" height="600"/>

In [ ]:
#table 7 (the mean high temperature for rainy and non-rainy days for each month of the year)
...